#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|refactore|fix|test|chore|doc|style)\: .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "- Mensagem do commit fora do padrão -"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood> <what was done>"
  echo "Allowed verbs in imperative mood: feat|refactore|fix|test|chore|doc|style"
  echo "Example: add login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
